qwerty-sc25/qwerty-sc25

.vscode/extensions.json, .vscode/settings.json, README.md
- Add member info
- Set prettier as default formatter
=> Init project with member info

client/.env.example, client/src/api/apiBuilder.ts, client/src/api/join/useJoin.ts, client/src/api/login/useLogin.ts, client/src/routes/_pathlessLayout/login.tsx, client/src/routes/_pathlessLayout/register.tsx, client/src/states/auth.ts, client/src/states/index.ts, client/src/types/role.ts
- 회원가입, 로그인 페이지에서 API 사용
- 회원가입, 로그인 페이지에서 API 사용
Closes #12, Closes #13
=> Use auth apis

chaekit-spring/src/main/java/qwerty/chaekit/controller/PublisherController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/UserController.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/PublisherJoinResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/UserJoinResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/global/jwt/JwtUtil.java, chaekit-spring/src/main/java/qwerty/chaekit/global/security/config/SecurityConfig.java, chaekit-spring/src/main/java/qwerty/chaekit/global/security/filter/login/LoginFilter.java, chaekit-spring/src/main/java/qwerty/chaekit/service/PublisherJoinService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/UserJoinService.java
join 및 login 시 accessToken과 id 응답 필드 추가
- body에 id, accessToken 추가
Closes #19 
postman. https://www.notion.so/Postman-1c52064200ba802693bed1b605cc8466
=> feat: add accessToken and id in json

client/src/api/admin/useGetBook.ts, client/src/api/admin/useGetBooks.ts, client/src/api/admin/useUploadBook.ts, client/src/api/apiBuilder.ts, client/src/api/login/useLogout.ts, client/src/component/AppBar.tsx, client/src/routes/_pathlessLayout/admin/books.tsx, client/src/routes/_pathlessLayout/admin/index.tsx, client/src/routes/_pathlessLayout/admin/route.tsx, client/src/routes/_pathlessLayout/admin/uploadBook.tsx, client/src/states/auth.ts, client/src/types/book.ts
ex) 회원가입 기능 구현
- 등록된 도서 불러오기
- 도서 업로드
- 기타 UI 개선
- 앱 바에서 로그인, 로그아웃
- 관리자로 로그인 시 관리자 페이지로 이동하는 버튼 표시
Closes #14
=> Add admin page

chaekit-spring/src/main/java/qwerty/chaekit/controller/AdminController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/GroupController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/HighlightController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/MainController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/GroupMember.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/GroupRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/GroupTag.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/GroupTagRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/ReadingGroup.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/Highlight.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/LoginResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/GroupFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/GroupListResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/GroupPostRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/GroupPostResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/GroupPutRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/HighlightPutRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/page/PageResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/global/config/swagger/LoginDocsController.java, chaekit-spring/src/main/java/qwerty/chaekit/global/init/AdminInitializer.java, chaekit-spring/src/main/java/qwerty/chaekit/global/security/config/SecurityConfig.java, chaekit-spring/src/main/java/qwerty/chaekit/global/security/filter/login/LoginFilter.java, chaekit-spring/src/main/java/qwerty/chaekit/service/EbookFileService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/GroupService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/HighlightService.java
모임 생성, 조회, 수정 기능 구현 기능 개발
- 누락된 하이라이트 업데이트 api 추가
- 모임 생성, 조회, 수정 기능 기본 구현
- 로그인 필터 Swagger 적용(LoginDocsController라는 가짜 컨트롤러 작성)
Closes #51 
Postman
=> Feat: 모임 생성, 조회, 수정 기능 구현

client/src/component/HighlightBrowserModal.tsx, client/src/component/SideNavigatorBar.tsx, client/src/component/groupCreate/GroupCreateModal.tsx, client/src/component/groupCreate/GroupEditForm.tsx, client/src/routes/_pathlessLayout/admin/index.tsx, client/src/routes/_pathlessLayout/groups/$groupId.tsx, client/src/routes/_pathlessLayout/groups/index.tsx, client/src/routes/_pathlessLayout/mypage/groups.tsx, client/src/routes/_pathlessLayout/mypage/index.tsx, client/src/routes/_pathlessLayout/mypage/route.tsx, client/src/types/groups.ts, client/src/types/highlight.ts
모임 정보 페이지 추가
- 루트 추가
- UI 설계 / 구현
Closes #53 
- swagger에 해당 API가 업데이트되지않았기때문에 실제 쿼리하는 부분은 제외됨
#112 #113 우선 머지 후 리베이스 하고 머지할 것
=> Add group info page

client/src/component/HighlightBrowserModal.tsx, client/src/component/SideNavigatorBar.tsx, client/src/component/groupCreate/GroupCreateModal.tsx, client/src/component/groupCreate/GroupEditForm.tsx, client/src/routes/_pathlessLayout/admin/index.tsx, client/src/routes/_pathlessLayout/mypage/groups.tsx, client/src/routes/_pathlessLayout/mypage/index.tsx, client/src/routes/_pathlessLayout/mypage/route.tsx, client/src/types/highlight.ts
- 루트 추가
- mypage
- mypage/groups
ex)
- 루트 추가
- 그룹 정보 수정 폼 추가
- 그룹 생성 모달 추가
Closes #52 
- swagger에 해당 API가 업데이트되지않았기때문에 실제 쿼리하는 부분은 제외됨
=> Add create group form

client/src/api/login/useAutoLogin.ts, client/src/api/login/useLogin.ts, client/src/api/login/useLogout.ts, client/src/routes/_pathlessLayout/route.tsx
=> Impl auto login

client/src/routes/reader.tsx, client/src/types/highlight.ts
코멘트, 반응 UI
- highlight api 사용 쿼리
- 코멘트 버튼, 입력창 추가
- 반응 버튼 추가
- 코멘트 표시
Closes #46
=> Add highlight comment and reaction

chaekit-spring/src/main/java/qwerty/chaekit/global/enums/ErrorCode.java, chaekit-spring/src/main/java/qwerty/chaekit/global/exception/BadRequestException.java, chaekit-spring/src/main/java/qwerty/chaekit/global/exception/CustomException.java, chaekit-spring/src/main/java/qwerty/chaekit/global/exception/ForbiddenException.java, chaekit-spring/src/main/java/qwerty/chaekit/global/exception/NotFoundException.java, chaekit-spring/src/main/java/qwerty/chaekit/global/security/resolver/LoginArgumentResolver.java, chaekit-spring/src/main/java/qwerty/chaekit/service/AdminService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/EbookFileService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/GroupService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/HighlightService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/MemberJoinHelper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/PublisherJoinService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/PublisherService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/UserJoinService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/UserService.java
error code enum으로 정리
ex)
- ErrorCode 작성
- 모든 예외에 ErrorCode로 치환
=> [REFACTOR] error code enum으로 정리

.github/workflows/destroy-client.yml, client/cdk/lib/ClientDeploymentStack.ts
클라이언트 배포 오류 수정
- 버킷 이름 중복을 피하기위해 `-chaekit-client` 접미어 추가
- destroy시에도 부트스트랩을 위해 클라이언트 빌드
-
=> Fix deployment

.github/workflows/deploy-dev-server.yml, chaekit-spring/chaekit-dev-task.json, chaekit-spring/chaekit-prod-task.json
deploy-dev-server.yml
chaekit-dev-task.json
chaekit-prod-task.json
=> [FIX] 배포 task 수정

chaekit-spring/build.gradle, chaekit-spring/src/main/resources/application.yml, chaekit-spring/src/main/resources/db/migration/V1__init_schema.sql
스키마 파일(db.migration.V1__init_schema.sql)을 통한 flyway 적용
- 스키마 추출
- flyway 설정
- 배포 이후 후속 조치로 spring.flyway.baseline-on-migration = false로 설정
=> [CHORE] DB flyway 설정

chaekit-spring/src/main/resources/application.yml
=> [CHORE] 배포 설정 변경

.github/workflows/deploy-client.yml
클라이언트에서 바뀐 API 엔드포인트 사용
- 배포된 클라이언트에서 바뀐 API 엔드포인트를 사용하도록 변경
=> [CHORE] 클라이언트에서 바뀐 API 엔드포인트 사용

client/src/routes/_pathlessLayout/groups/$groupId.tsx, client/src/types/activity.ts, client/src/types/groups.ts
모임 메인 페이지에서 등록된 활동 정보 표시
- 모임 메인 페이지에서 등록된 활동 정보 표시
Closes #57
=> [TASK 4-2-3][FE] 모임 메인 페이지에서 등록된 활동 정보 표시

chaekit-spring/src/main/java/qwerty/chaekit/controller/group/GroupController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/GroupMember.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/ReadingGroup.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/GroupJoinResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/GroupService.java, chaekit-spring/src/main/resources/db/migration/V3__add_groupmember_approve.sql
ex) 모임가입, 모임승인 기능 구현
ex)
- ReaadingGroup도메인수정
- GroupController추가
- Flyway v3추가
- GroupService내용추가
Closes #이슈번호
ex) Postman에 모임가입,독서모임가입승인 생성
=> feat 가입,승인코드 작성중2

.github/workflows/deploy-dev-server.yml, chaekit-spring/README.md
=> [FIX] workflow 수정

client/api.json, client/src/api/api.gen.ts, client/src/component/groupCreate/GroupCreateModal.tsx, client/src/routes/_pathlessLayout/admin/books.tsx, client/src/routes/_pathlessLayout/register.tsx, client/src/routes/reader.tsx
API 클라이언트 업데이트
- API 클라이언트 업데이트
=> [CHORE] API 클라이언트 업데이트

client/src/routes/_pathlessLayout/groups/$groupId.tsx, client/src/routes/_pathlessLayout/groups/$groupId/index.tsx, client/src/routes/_pathlessLayout/groups/$groupId/manage/index.tsx, client/src/routes/_pathlessLayout/groups/$groupId/manage/joinRequests.tsx, client/src/routes/_pathlessLayout/groups/$groupId/manage/route.tsx
모임 가입 신청
- [TASK 4-5-2] 가입 신청 버튼 및 UI
- [TASK 4-5-4] 모임지기 가입 승인 관리 페이지
Closes #68 
Closes #70 
- 일부 API 미구현
=> [TASK 4-5-2][TASK 4-5-4] 모임 가입 신청

client/src/component/PageNavigation.tsx, client/src/component/groupList.tsx, client/src/routes/_pathlessLayout/books/index.tsx
전자책 검색 페이지 구현
- 전자책 검색 페이지 구현
Closes #28 
- 검색 API 미완성으로 검색 기능 미포함
=> [TASK 2-1-2][FE] 전자책 검색 페이지 구현

chaekit-spring/src/main/resources/application.yml
=> [TEST] Redis 배포 수정 테스트

chaekit-spring/chaekit-dev-task.json, chaekit-spring/src/main/java/qwerty/chaekit/global/init/AdminInitializer.java, chaekit-spring/src/main/resources/application-dev.yml, chaekit-spring/src/main/resources/application-local.yml
=> [CHORE] 배포 환경 버그 수정 완료

chaekit-spring/src/main/java/qwerty/chaekit/controller/ebook/EbookController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/group/GroupController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/member/publisher/PublisherController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/member/user/UserController.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/ebook/upload/EbookPostRequest.java
Swagger form 방식 문서화 문제 수정
- @PostMapping의 consumes 값을 MediaType.MULTIPART_FORM_DATA_VALU로 지정
- @Paramter(hidden = true) 추가
=> [FIX] form 방식 문서화 문제 수정

client/api.json, client/src/api/api.gen.ts, client/src/api/login/useLogin.ts, client/src/component/AppBar.tsx, client/src/component/groupCreate/GroupCreateModal.tsx, client/src/routes/_pathlessLayout/admin/uploadBook.tsx, client/src/routes/_pathlessLayout/login.tsx, client/src/routes/_pathlessLayout/register.tsx, client/src/states/auth.ts
이메일 인증 과정 추가
- 회원가입 시 이메일 인증 과정 추가
- 앱 바에 `마이페이지`버튼 대신 유저 프로필 아바타 표시
- 편의성 개선
- 비밀번호, 인증코드 등 텍스트 인풋에서  엔터 키 입력시 아래 버튼 클릭
#175
=> [TASK][FE] 가입 시 이메일 인증

chaekit-spring/src/main/java/qwerty/chaekit/controller/highlight/HighlightController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/highlight/comment/CommentController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/highlight/reaction/ReactionController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/entity/Highlight.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/entity/comment/HighlightComment.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/entity/reaction/HighlightReaction.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/entity/reaction/ReactionType.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/comment/HighlightCommentJpaRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/comment/HighlightCommentRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/comment/HighlightCommentRepositoryImpl.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/reaction/HighlightReactionJpaRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/reaction/HighlightReactionRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/reaction/HighlightReactionRepositoryImpl.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/comment/CommentRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/comment/CommentResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/reaction/ReactionRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/reaction/ReactionResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/global/enums/ErrorCode.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/HighlightService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/comment/CommentService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/reaction/ReactionService.java, chaekit-spring/src/main/resources/db/migration/V10__add_comment_id_to_highlight_reaction.sql, chaekit-spring/src/main/resources/db/migration/V9__add_parent_id_to_highlight_comment.sql
ex) 댓글,이모티콘 crud
ex)
- 댓글추가하기, 이모티콘 추가하기완료
- 이모티콘 종류는 src/main/java/qwerty/chaekit/domain/highlight/entity/reaction/ReactionType에서 확인가능
- 이모티콘은 개별삭제 가능함.
- 동일댓글에는 개인당같은 이모티콘은 한개만가능하고 댓글이없는경우 이모티콘은 사용할수없음.
Closes #45 
ex) 
Post방식 : api/highlights/{highlightsId}/reactions -> 이모티콘생성
* body값에 commentId값이 없으면 하이라이트에 대한 반응
* body값에 commentId값이 존재한다면 commentId값에 대한 반응 
Delete방식 : api/highlights/reactions/{reactionId} -> 이모티콘삭제
Get방식 : api/highlights/{highlightsId}/reactions->하이라이트에 대한 반응조회
ex)
=> [TASK 3-2-3][BE] 코멘트, 반응 CRUD

client/src/api/api.ts, client/src/api/login/useAutoLogin.ts, client/src/api/login/useAutoTokenRefresh.ts, client/src/api/login/useLogout.ts, client/src/api/login/useRefresh.ts, client/src/routes/_pathlessLayout/route.tsx, client/src/routes/reader.tsx, client/src/states/auth.ts, client/src/util/getLoggedInUserFromLocalStorage.ts
refresh token을 통한 자동 로그인 갱신
- refresh token 저장
- 토큰 만료 시 자동 갱신
- 로그아웃 시, 토큰 무효화(/api/logout 요청)
Closes #185 
- 매 5분마다 refresh 시도
- 세션 만료 시 alert
=> [TASK 1-1-8] refresh token 처리

client/api.json, client/src/api/api.gen.ts, client/src/routes/_pathlessLayout/admin/books.tsx, client/src/routes/_pathlessLayout/admin/uploadBook.tsx, client/src/routes/_pathlessLayout/books/index.tsx, client/src/routes/_pathlessLayout/login.tsx
=> [CHORE] Update api client

client/src/api/api.ts
액세스 토큰 보낼 때 `Bearer`접두어 추가
액세스 토큰 보낼 때 `Bearer`접두어 추가
=> [FIX] 토큰 접두사 수정

.github/workflows/deploy-dev-server.yml, chaekit-spring/README.md
=> [FIX] add permission for gh page

client/src/routes/reader.$bookId.tsx, client/src/util/loadBook.ts
하이라이트 공개 범위 변경 UI 구현
- 서버에서 책 다운로드
- 로컬에 책 캐시
- 작성자일경우 하이라이트에 공개범위 수정 메뉴 표시
Closes #44
=> [TASK 3-2-2][FE] 메모 공개 범위 UI (공개범위 드롭다운)

client/src/component/HighlightBrowserModal.tsx, client/src/routes/_pathlessLayout/mypage/index.tsx
마이페이지에서 작성한 메모 표시
- 하이라이트 브라우저가 서버에서 하이라이트를 가져오도록 수정
- "내 모든 하이라이트" 필터 구현
- 마이페이지에 하이라이트 브라우저 여는 버튼 추가
- 하이라이트 브라우저 백드롭 클릭시 창이 닫히도록 수정
Closes #50
=> [TASK 3-3-4][FE] 마이페이지에서 작성한 메모 표시

client/src/api/api.ts, client/src/api/login/useAutoTokenRefresh.ts, client/src/api/login/useInvalidateQueriesOnAuthChange.ts, client/src/api/login/useRefresh.ts, client/src/routes/_pathlessLayout/route.tsx, client/src/routes/reader.$bookId.tsx, client/src/states/auth.ts
액세스 토큰 만료시 자동 갱신
- 액세스 토큰 만료시 자동 갱신
- 토큰 정보 변경시 다시 쿼리
=> [FIX] 액세스 토큰 만료시 자동 갱신

chaekit-spring/src/main/java/qwerty/chaekit/controller/group/GroupController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/member/verification/EmailVerificationController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightRepositoryImpl.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/HighlightFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/global/config/SwaggerConfig.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/GroupService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/HighlightService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/MemberJoinHelper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/admin/AdminService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/verification/EmailVerificationService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/util/EmailNotificationService.java, chaekit-spring/src/test/java/qwerty/chaekit/service/AdminServiceTest.java
하이라이트에 사용자 정보 추가
- 문서화 버그 수정
- member/email/EmailService -> util/EmailNotificationService 리팩토링
- 하이라이트 조회에 사용자 정보(authorId, authorName, authorProfileImageURL) 추가
=> [FIX] 하이라이트에 사용자 정보 추가

chaekit-spring/src/main/java/qwerty/chaekit/controller/group/DiscussionController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/discussion/Discussion.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/discussion/DiscussionPatchRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/DiscussionService.java, client/api.json
=> [FIX] 스웨거 버그 수정

chaekit-spring/src/test/java/qwerty/chaekit/service/group/DiscussionServiceTest.java
=> [FIX] 테스트에 변경사항 반영

client/src/api/api.ts, client/src/api/login/useLogin.ts, client/src/api/login/useLogout.ts, client/src/api/login/useRefresh.ts
클로저에 캡쳐된 토큰을 사용해 토큰 갱신 후에도 이전 토큰을 사용하는 문제 해결
=> [FIX] 클로저에 캡쳐된 토큰을 사용하는 문제 수정

chaekit-spring/src/main/java/qwerty/chaekit/controller/group/ActivityController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/highlight/HighlightController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/repository/ActivityRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/entity/Highlight.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/ActivityFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/HighlightFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/HighlightPostRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/HighlightPostResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/global/enums/ErrorCode.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/ActivityService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/HighlightService.java, chaekit-spring/src/main/resources/db/migration/V16__add_highlightcontent_column.sql, chaekit-spring/src/test/java/qwerty/chaekit/integration/HighlightServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/ActivityServiceTest.java
ex) 활동 조회시 책 내용도 전달,
개별활동조회기능 추가
ex)
- 활동 조회시 책 내용도 전달,
개별활동조회기능 추가
Closes #58 
ex) 
GET방식 - /api/activities/{activityId} ->개별활동조회
GET방식 - /api/activities ->책내용조회
POST방식 - /api/highlights - 하이라이트 등록
GET - /api/highlights - 하이라이트 조회
GET - /api/highlights/{id} - 하이라이트 개별조회
=> [TASK 4-3-1][BE] 모임원별 독서 진행률 데이터 수집 로직 및 조회 API

client/api.json, client/src/api/api.gen.ts, client/src/component/HighlightBrowserModal.tsx, client/src/routes/_pathlessLayout/admin/uploadBook.tsx, client/src/routes/reader.$bookId.tsx
=> [CHORE] 클라이언트 API 업데이트

client/src/component/AppBar.tsx, client/src/component/BookList.tsx, client/src/component/BookSearchInput.tsx, client/src/component/CreditPurchaseModal.tsx, client/src/component/LinkButton.tsx, client/src/component/LinkCardActionArea.tsx, client/src/component/_pathlessLayout/groups/$groupId/ActivityCard.tsx, client/src/component/groupList.tsx, client/src/routes/_pathlessLayout/books/$bookId.tsx, client/src/routes/_pathlessLayout/books/index.tsx, client/src/routes/_pathlessLayout/index.tsx, client/src/routes/_pathlessLayout/mypage/books.tsx, client/src/routes/_pathlessLayout/mypage/groups.tsx, client/src/routes/_pathlessLayout/mypage/route.tsx, client/src/routes/_pathlessLayout/posts/index.tsx, client/src/types/activity.ts
책 관련 UI 개선 및 기능 추가
- 활동에서 도서 리더 페이지로 이동
- 도서 구매 페이지 추가
- 도서 검색 구현
- 도서 자동완성에 책 표지와 글쓴이 표시
- 메인화면에 도서 섹션 추가
- 구매한 도서 목록 추가
- 잔액 부족시 크레딧 충전 모달 팝업
- 앱바에서 버튼 시인성 개선
Closes #37 
Closes #33
=> [FEAT][TASK 2-4-2][TASK 2-2-4] 책 관련 UI 개선 및 기능 추가

chaekit-spring/src/main/java/qwerty/chaekit/controller/ebook/EbookController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/group/ActivityController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/Activity.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/member/user/UserProfile.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/ebook/EbookFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/ActivityFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookPurchaseService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/ActivityService.java, chaekit-spring/src/test/java/qwerty/chaekit/integration/ActivityServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/integration/HighlightServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/ActivityServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/util/TestFixtureFactory.java
프론트엔드에서 요청한 UI 요구사항 반영
1. ActivityFetchResponse에 coverImageUrl(String) 추가
2. ActivityFetchResponse에 isParticipant(boolean) 추가
3. EbookFetchResponse에 isPurchased(boolean) 추가
4. EbookFetchResponse에 price(int) 추가
5. GroupFetchResponse에 myMembershipStatus에 "OWNED" 값 추가
6. 토론 삭제 전 댓글 존재하는지 확인 후 예외 처리(DISCUSSION_HAS_COMMENTS)
=> [FIX] UI 요구사항 반영

chaekit-spring/src/main/java/qwerty/chaekit/controller/ebook/EbookController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/group/ActivityController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/ReadingGroup.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/activitymember/ActivityMemberRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/ActivityFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/response/GroupFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/mapper/GroupMapper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/ActivityService.java, chaekit-spring/src/main/resources/db/migration/V21__fix_null_percentage.sql
버그 수정
- 전자책 목록 조회시 로그인 필수 해제
- 내 활동 조회 api 수정
- 그룹 조회시, 리더 정보 출력
POST /api/reading-progress/1/save
GET /api/reading-progress/1/save
GET /api/reading-progress/activities/1
GET /api/users/me/activities?bookId=1
=> [FIX] 자잘한 버그 수정

chaekit-spring/src/main/java/qwerty/chaekit/domain/discussionhighlight/DiscussionHighlight.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/discussionhighlight/DiscussionHighlightRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/discussion/Discussion.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/discussion/DiscussionHighlight.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/entity/Highlight.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightJpaRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightRepositoryImpl.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/discussion/DiscussionDetailResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/discussion/DiscussionFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/discussion/DiscussionPatchRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/discussion/DiscussionPostRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/discussion/DiscussionSummaryResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/HighlightFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/mapper/DiscussionMapper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/DiscussionService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/HighlightService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/comment/HighlightCommentService.java, chaekit-spring/src/main/resources/db/migration/V22__add_table_discussion_highlight.sql, chaekit-spring/src/test/java/qwerty/chaekit/service/group/DiscussionServiceTest.java
토론에 하이라이트 인용한것을 저장.
하이라이트에는 인용된 토론 표시.
토론에는 인용된 하이라이트 표시.
토론 등록 및 수정 시 -> highlightsIds 지정 및 재등록
토론 조회 시 -> highlightIds 필드 응답
하이라이트 조회 시 -> relatedDiscussion 필드 응답
=> [FEAT] 토론 하이라이트 인용

chaekit-spring/src/main/java/qwerty/chaekit/controller/group/ActivityController.java, chaekit-spring/src/main/java/qwerty/chaekit/mapper/GroupMapper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/ActivityService.java, client/api.json, client/src/api/api.gen.ts, client/src/component/AppBar.tsx, client/src/component/CreditPurchaseModal.tsx, client/src/component/HighlightCard.tsx, client/src/component/HighlightCreationModal.tsx, client/src/component/HighlightSumarryCard.tsx, client/src/component/LinkChip.tsx, client/src/component/NotificationButton.tsx, client/src/component/_pathlessLayout/groups/$groupId/ActivityCard.tsx, client/src/routes/_pathlessLayout/books/$bookId.tsx, client/src/routes/_pathlessLayout/groups/$groupId/activities/$activityId/discussions/$discussionId/index.tsx, client/src/routes/credits.payment.success.tsx, client/src/routes/reader.$bookId.tsx, client/src/types/discussion.ts, client/src/types/highlight.ts, client/src/types/notification.ts, client/src/types/paymentSuccessMessage.ts
프론트, 백엔드 통합 버그 해결
- 로그인하지 않은 사용자도 독서 진행률 볼 수 있게 수정(server)
- 대기중인 사용자의 프로필 사진 버그 해결(server)
- 리더 함께읽기 스낵바 자동으로 사라지게 변경(client)
- 리더 하이라이트 생성 버튼 마지막 마우스 위치에 나타나도록 수정(client)
- 상단바에 알림 버튼 표시(client)
- 책 보유시 구매버튼 비활성화(client)
- 리더 하이라이트에서 인용한 토론으로 이동(client)
- 크레딧 결제 구현(client)
=> [HOTFIX] 자잘한 버그 수정

client/src/routes/reader.$bookId.tsx
clientX, clientY 대신 screenX, screenY 사용
=> [FIX] 하이라이트 생성 버튼 임시 수정

chaekit-spring/src/main/java/qwerty/chaekit/controller/group/GroupChatController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/group/GroupController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/group/GroupReviewController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/highlight/comment/HighlightCommentController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/highlight/reaction/HighlightReactionController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/review/GroupReview.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/review/GroupReviewRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/review/GroupReviewTag.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/review/GroupReviewTagRelation.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/review/GroupReviewTagRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/notification/entity/NotificationType.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/review/GroupReviewFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/review/GroupReviewPostRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/review/GroupReviewStatsResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/review/TagStatDto.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/member/LoginResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/global/security/filter/login/LoginFilter.java, chaekit-spring/src/main/java/qwerty/chaekit/mapper/GroupReviewMapper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookPolicy.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/GroupReviewService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/publisher/PublisherJoinService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/user/UserJoinService.java, chaekit-spring/src/main/resources/db/migration/V24__create_group_review.sql
- 모임 후기 등록 및 조회 구현
- 후기 태그 관련 통계 조회 구현
Related #76 #77 
Closes #76 #77 
POSTMAN
=> [TASK 4-8-1][BE] 모임 후기 등록 API

chaekit-spring/src/main/java/qwerty/chaekit/controller/ebook/EbookController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/ebook/EbookRequestController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/member/publisher/PublisherController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/Ebook.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/repository/EbookJpaRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/repository/EbookRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/repository/EbookRepositoryImpl.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/request/EbookRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/request/EbookRequestRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/request/EbookRequestStatus.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/review/GroupReview.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/review/GroupReviewTagRelation.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/member/Member.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/member/publisher/PublisherProfile.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/member/user/UserProfile.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/ebook/request/EbookRequestFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/ebook/request/EbookRequestRejectRequest.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/ebook/upload/EbookPostResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/review/GroupReviewFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/global/enums/ErrorCode.java, chaekit-spring/src/main/java/qwerty/chaekit/global/jwt/JwtUtil.java, chaekit-spring/src/main/java/qwerty/chaekit/global/security/filter/login/LoginFilter.java, chaekit-spring/src/main/java/qwerty/chaekit/mapper/EbookRequestMapper.java, chaekit-spring/src/main/java/qwerty/chaekit/mapper/GroupReviewMapper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookFileService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/util/EntityFinder.java, chaekit-spring/src/main/resources/db/migration/V25__create_ebook_request.sql
출판사가 전자책을 등록하고 관리자가 승인하는 일련의 과정에서 필요한 기능을 구현한다.
- 전자책 요청
- 전자책 승인
- 전자책 반려
- 전자책 요청 목록 조회
- 등록된 전자책 다운로드(출판사용)
- 미등록된 전자책 다운로드
- 태그 수정 버그 해결
- 모임 리뷰에 활동 정보, 책 정보 추가
Closes #90 #91 #99 
POSTMAN
POST /api/books
GET /api/books/{bookId}/publisher-download
POST /api/book-requests/{requestId}/approve
POST /api/book-requests/{requestId}/reject
GET /api/book-requests/{requestId}/download
GET /api/publishers/me/books
=> [TASK][BE] 출판사 전자책 등록 관련 API 작업

client/api.json, client/src/api/api.gen.ts, client/src/component/GroupReviewCard.tsx, client/src/component/HighlightCard.tsx, client/src/component/HighlightCommentCard.tsx, client/src/component/HighlightSumarryCard.tsx, client/src/types/groupReview.ts
모임 후기 추가 다이얼로그
기존 모임 후기 리스트 & 모임 후기 작성 API 연결
태그 통계 UI 개선
태그 통계 & 후기 리스트 pagination
#77 
ex) Postman으로 /api/join 요청
ex) 에러 메시지 형식은 ErrorResponse로 통일함
=> [FEAT] 모임 후기 등록

.github/workflows/deploy-prod-server.yml, chaekit-spring/chaekit-prod-task.json
=> [CHORE] 메인 서버 배포 전 환경변수 설정

chaekit-spring/src/main/java/qwerty/chaekit/global/security/resolver/UserToken.java, chaekit-spring/src/main/java/qwerty/chaekit/global/security/service/CustomUserDetailsService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookFileService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookPolicy.java, chaekit-spring/src/main/java/qwerty/chaekit/service/ebook/EbookPurchaseService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/ActivityPolicy.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/HighlightPolicy.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/MemberJoinHelper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/admin/AdminService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/publisher/PublisherJoinService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/publisher/PublisherService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/user/UserJoinService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/member/user/UserService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/util/EmailNotificationService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/util/EntityFinder.java, chaekit-spring/src/test/java/qwerty/chaekit/service/AdminServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/GroupServiceTest.java
출판사에게 이메일 알림 전송
- 전자책 반려시 이메일 알림 추가
- Transactional 실수 해결(크레딧이 차감되지 않는 버그)
- 모임 CRUD 단위 테스트 추가
- 관리자 기능 단위 테스트 추가
Closes #93 
JUNIT5
=> [TASK 5-2-4][BE] 반려 사유 저장 및 출판사에게 이메일 알림 전송

chaekit-spring/README.md, chaekit-spring/src/main/java/qwerty/chaekit/ChaekitApplication.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/repository/GroupRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/review/GroupReview.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/comment/repository/HighlightCommentRepositoryImpl.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/DiscussionCommentService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/GroupChatService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/GroupService.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/ActivityPolicyTest.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/ActivityServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/DiscussionCommentServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/GroupMemberServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/GroupReviewServiceTest.java, chaekit-spring/src/test/java/qwerty/chaekit/service/group/GroupServiceTest.java
group 패키지에 속하는 서비스에 대한 단위 테스트
- ActivityPolicy 테스트
- GroupMemberService 테스트
- GroupReviewService 테스트
- GroupService 테스트
=> [TEST] Unit Test for Group Service

client/src/component/BookRequestDialog.tsx, client/src/component/CommentSection.tsx, client/src/component/DiscussionForm.tsx, client/src/component/GroupReviewCard.tsx, client/src/component/HighlightBrowserModal.tsx, client/src/component/HighlightCard.tsx, client/src/hooks/useBookUpload.ts, client/src/routes/groups/$groupId/activities/$activityId/discussions/$discussionId/index.tsx, client/src/routes/index.tsx
다이얼로그 개선 외
출판사 책 등록 다이얼로그 개선 등
Closes #이슈번호
ex) Postman으로 /api/join 요청
ex) 에러 메시지 형식은 ErrorResponse로 통일함
=> [CHORE] 다이얼로그 개선 외

chaekit-spring/nginx/default.conf
=> [FIX] nginx 복구

chaekit-spring/Dockerfile, chaekit-spring/docker-compose.yml, chaekit-spring/src/main/java/qwerty/chaekit/ChaekitApplication.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/ebook/ReadingProgressController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/group/ActivityController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/history/ReadingProgressHistory.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/ebook/history/ReadingProgressHistoryRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/activitymember/ActivityMemberRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/dto/ActivityScoreDto.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/group/activity/repository/ActivityRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightJpaRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightRepositoryImpl.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/activity/ActivityScoreResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/group/response/GroupFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/HighlightPreviewResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/dto/statistics/ReadingProgressHistoryResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/global/init/ReadingProgressHistoryInitializer.java, chaekit-spring/src/main/java/qwerty/chaekit/global/jwt/JwtUtil.java, chaekit-spring/src/main/java/qwerty/chaekit/mapper/GroupMapper.java, chaekit-spring/src/main/java/qwerty/chaekit/service/group/ActivityService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/HighlightService.java, chaekit-spring/src/main/java/qwerty/chaekit/service/statistics/ReadingProgressHistoryService.java, chaekit-spring/src/main/resources/db/migration/V28__create_reading_progress_history.sql
활동 통계 api 개발
- 메모리 사용량 제한
- NEW: 읽기 진행률 히스토리 저장 및 조회(cron)
- NEW: 상위 5명의 활동 점수 계산 및 조회
- NEW: 최근 메모 조회(특정 활동에서)
- FIX: 모임 조회시, 자동 가입 여부 응답
Closes #79 
Postman
x
=> [TASK 4-9-1] 통계 기반 활동 요약 기능

chaekit-spring/src/main/java/qwerty/chaekit/config/WebSocketConfig.java, client/bun.lock, client/package.json, client/src/component/AppBar.tsx, client/src/component/CreditPurchaseModal.tsx, client/src/component/GroupChat.tsx, client/src/component/GroupList.tsx, client/src/component/NotificationButton.tsx, client/src/component/_pathlessLayout/groups/$groupId/ActivityCard.tsx, client/src/routes/groups/$groupId/index.tsx, client/src/routes/groups/index.tsx, client/src/routes/index.tsx, client/src/routes/mypage/index.tsx, client/src/types/groupMessage.ts, client/src/utils/useThrottle.ts
그룹 채팅 추가
- 그룹 채팅 추가
- 알림 발생시 알림 표시
Closes #73
=> [FEAT] 그룹 채팅 추가

chaekit-spring/nginx/default.conf
nginx에서 웹소켓 지원
nginx에서 웹소켓 지원
#276
=> [FIX] nginx에서 웹소켓 지원

chaekit-spring/src/main/java/qwerty/chaekit/dto/highlight/HighlightFetchResponse.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/HighlightService.java
하이라이트 조회에 응답 내용 보완
하이라이트 조회에 응답 내용 보완
- 도서 정보
- 모임 정보
- 생성일자
x
Postman
마이페이지에 하이라이트(메모) 관리 유저스토리를 고려하여 보완
=> [FEAT] 하이라이트 조회에 응답 내용 보완(도서 정보, 모임 정보, 생성일 정보)

client/api.json, client/src/api/api.gen.ts, client/src/component/ActivitySelectModal.tsx, client/src/component/HighlightBrowserModal.tsx
하이라이트 브라우저 기능 업그레이드
- 하이라이트 쿼리 수정
- 특정 활동 선택 기능 추가
- 공개 기능 추가
- 책, 작성자 정보 표시
=> [FEAT] 하이라이트 브라우저 기능 업그레이드

chaekit-spring/src/main/java/qwerty/chaekit/controller/highlight/HighlightController.java, chaekit-spring/src/main/java/qwerty/chaekit/controller/member/user/UserController.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightRepository.java, chaekit-spring/src/main/java/qwerty/chaekit/domain/highlight/repository/HighlightRepositoryImpl.java, chaekit-spring/src/main/java/qwerty/chaekit/service/highlight/HighlightService.java, chaekit-spring/src/main/resources/application.yml, chaekit-spring/src/test/java/qwerty/chaekit/integration/HighlightServiceTest.java
하이라이트 조회에 키워드 검색 기능 추가
- getHighlights에 keyword 쿼리파라미터 추가
- getMyHighlights에 keyword 쿼리파라미터 추가
Postman
x
=> [FEAT] 하이라이트 조회에 키워드 검색 기능 추가

client/src/routes/reader.$bookId.tsx
리더 페이지에 멤버 읽기 진행률 표시
리더 페이지에 멤버 읽기 진행률 표시
=> [FEAT] 리더 페이지에 멤버 읽기 진행률 표시

chaekit-spring/Dockerfile, chaekit-spring/docker-compose.yml
Dockerfile에 타임존 버그 수정(한국 기준으로 변경)
Dockerfile에 타임존 버그 수정(한국 기준으로 변경)
=> [FIX] Dockerfile에 타임존 버그 수정(한국 기준으로 변경)

client/src/component/GroupChat.tsx, client/src/component/HighlightCard.tsx, client/src/component/HighlightCreationModal.tsx, client/src/routes/reader.$bookId.tsx
리더에 비공개 하이라이트 표시
- 리더에 비공개 하이라이트 표시
- 비공개 하이라이트 공개 기능 수정
=> [FEAT] 리더에 비공개 하이라이트 표시

client/api.json, client/src/api/api.gen.ts, client/src/component/GroupList.tsx, client/src/component/UserProfileEditModal.tsx, client/src/routes/groups/index.tsx, client/src/routes/index.tsx, client/src/routes/mypage/index.tsx
마이페이지 일부 구현
user profile section
group list small medium large
Closes #이슈번호
ex) Postman으로 /api/join 요청
ex) 에러 메시지 형식은 ErrorResponse로 통일함
=> [Feat] 마이페이지 일부 구현

client/api.json, client/src/api/api.gen.ts, client/src/component/GroupList.tsx, client/src/component/UserProfileEditModal.tsx, client/src/component/_pathlessLayout/groups/$groupId/CurrentActivityCard.tsx, client/src/component/_pathlessLayout/groups/$groupId/PastActivityCard.tsx, client/src/routes/groups/index.tsx, client/src/routes/index.tsx, client/src/routes/mypage/index.tsx, client/src/types/activity.ts
활동카드 아이콘 수치 반영
activity type 수정
활동카드 아이콘에 수치 반영
ex) Postman으로 /api/join 요청
ex) 에러 메시지 형식은 ErrorResponse로 통일함
=> [FIX] 활동카드 아이콘 수치 반영

.github/workflows/deploy-prod-server.yml, chaekit-spring/chaekit-prod-task.json
=> [DEPLOY] 카프카 환경변수 추가
